# Generated by Django 4.2.1 on 2024-01-13 19:04

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=post.models.upload_to, validators=[post.models.post_media_type_validation]),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to=post.models.upload_to, validators=[post.models.post_media_type_validation]),
        ),
    ]
